### ISSUE TITLE
runtests.py gives ConftestImportFailure: ImportMismatchError

### ISSUE THREAD

**Issue by alannnna** [adamchainz/django-mysql#359] opened 2017-05-03 20:21 UTC
Summary: Testing for Django 1.11 support, but can't run tests.

I wanted to see if django-mysql works with Django 1.11, so I followed the steps [here](http://django-mysql.readthedocs.io/en/latest/contributing.html#get-started); unfortunately, step 5 (`./runtests.py`) isn't working for me due to some conftest issue. I've verified my database connection works. 

This is the output I get:
```
$ ./runtests.py 
======================================= test session starts ========================================
platform darwin -- Python 2.7.10, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
Django settings: settings (from environment variable)
Django version: 1.11.0.final.1
MySQL version: 5.7.18
rootdir: /Users/me/things/django-mysql, inifile: setup.cfg
plugins: super-check-1.0.0, django-3.0.0, backports.unittest-mock-1.2
collected 0 items / 1 errors 

============================================== ERRORS ==============================================
________________________________________ ERROR collecting  _________________________________________
venv/lib/python2.7/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
venv/lib/python2.7/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
venv/lib/python2.7/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
venv/lib/python2.7/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
venv/lib/python2.7/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
venv/lib/python2.7/site-packages/py/_path/common.py:368: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
venv/lib/python2.7/site-packages/_pytest/main.py:672: in _recurse
    ihook = self.gethookproxy(path)
venv/lib/python2.7/site-packages/_pytest/main.py:575: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
venv/lib/python2.7/site-packages/_pytest/config.py:315: in _getconftestmodules
    mod = self._importconftest(conftestpath)
venv/lib/python2.7/site-packages/_pytest/config.py:340: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: ImportMismatchError('tests.conftest', '/Users/me/things/django-mysql/tests/conftest.py', local('/Users/me/things/django-mysql/venv/lib/python2.7/site-packages/tests/conftest.py'))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================== 1 error in 0.35 seconds ======================================
```

I've also tried with Django 1.10 installed instead of 1.11 (because 1.11 gets installed when running `pip install -r requirements.txt`). I get the same stack trace.

Help would be greatly appreciated.

**Comment by adamchainz** [comment] 2017-05-03 20:46
I run the tests under `tox` these days, if you `pip install tox` then `tox -e py36-django111` it should work. Will look into conftest issue.

**Comment by alannnna** [comment] 2017-05-04 18:58
Unfortunately, I couldn't get that to work. After fiddling with it a bit, I'm still back at the same error. This is the output I get after a fresh checkout, pip install inside a virtualenv, and running the tox command for Python 3.6 and Django 1.10:
```
$ tox -e py36-django110
GLOB sdist-make: /Users/me/things/django-mysql/setup.py
py36-django110 create: /Users/me/things/django-mysql/.tox/py36-django110
py36-django110 installdeps: Django>=1.10,<1.11, -rrequirements/requirements-testing.txt
py36-django110 inst: /Users/me/things/django-mysql/.tox/dist/django-mysql-1.1.1.zip
py36-django110 installed: appdirs==1.4.3,backports.unittest-mock==1.2,configparser==3.5.0,coverage==4.2,Django==1.10.7,django-mysql==1.1.1,docutils==0.12,enum34==1.1.6,flake8==3.0.4,funcsigs==1.0.2,mariadb-dyncol==1.2.0,mock==2.0.0,mysqlclient==1.3.7,nose-parameterized==0.5.0,packaging==16.8,pbr==1.10.0,py==1.4.31,pycodestyle==2.0.0,pyflakes==1.2.3,pyparsing==2.2.0,pytest==3.0.2,pytest-django==3.0.0,pytest-super-check==1.0.0,six==1.10.0,sqlparse==0.2.1
py36-django110 runtests: PYTHONHASHSEED='1218142498'
py36-django110 runtests: commands[0] | coverage run -p --source=django_mysql ./runtests.py
======================================= test session starts ========================================
platform darwin -- Python 3.6.1, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
Django settings: settings (from environment variable)
Django version: 1.10.7.final.0
MySQL version: 5.7.18
rootdir: /Users/me/things/django-mysql, inifile: setup.cfg
plugins: super-check-1.0.0, django-3.0.0, backports.unittest-mock-1.2
collected 0 items / 1 errors 

============================================== ERRORS ==============================================
________________________________________ ERROR collecting  _________________________________________
.tox/py36-django110/lib/python3.6/site-packages/_pytest/main.py:570: in gethookproxy
    return self._fs2hookproxy[fspath]
E   KeyError: local('/Users/me/things/django-mysql/venv/lib/python2.7/site-packages/tests')

During handling of the above exception, another exception occurred:
.tox/py36-django110/lib/python3.6/site-packages/_pytest/config.py:301: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('/Users/me/things/django-mysql/venv/lib/python2.7/site-packages/tests')

During handling of the above exception, another exception occurred:
.tox/py36-django110/lib/python3.6/site-packages/_pytest/config.py:332: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/Users/me/things/django-mysql/venv/lib/python2.7/site-packages/tests/conftest.py')

During handling of the above exception, another exception occurred:
.tox/py36-django110/lib/python3.6/site-packages/_pytest/config.py:338: in _importconftest
    mod = conftestpath.pyimport()
.tox/py36-django110/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('tests.conftest', '/Users/me/things/django-mysql/tests/conftest.py', local('/Users/me/things/django-mysql/venv/lib/python2.7/site-packages/tests/conftest.py'))

During handling of the above exception, another exception occurred:
.tox/py36-django110/lib/python3.6/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
.tox/py36-django110/lib/python3.6/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
.tox/py36-django110/lib/python3.6/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
.tox/py36-django110/lib/python3.6/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
.tox/py36-django110/lib/python3.6/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
.tox/py36-django110/lib/python3.6/site-packages/py/_path/common.py:367: in gen
    dirs = self.optsort([p for p in entries
.tox/py36-django110/lib/python3.6/site-packages/py/_path/common.py:368: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
.tox/py36-django110/lib/python3.6/site-packages/_pytest/main.py:672: in _recurse
    ihook = self.gethookproxy(path)
.tox/py36-django110/lib/python3.6/site-packages/_pytest/main.py:575: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
.tox/py36-django110/lib/python3.6/site-packages/_pytest/config.py:315: in _getconftestmodules
    mod = self._importconftest(conftestpath)
.tox/py36-django110/lib/python3.6/site-packages/_pytest/config.py:340: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: ImportMismatchError('tests.conftest', '/Users/me/things/django-mysql/tests/conftest.py', local('/Users/me/things/django-mysql/venv/lib/python2.7/site-packages/tests/conftest.py'))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================== 1 error in 0.89 seconds ======================================
ERROR: InvocationError: '/Users/me/things/django-mysql/.tox/py36-django110/bin/coverage run -p --source=django_mysql ./runtests.py'
_____________________________________________ summary ______________________________________________
ERROR:   py36-django110: commands failed
```

**Comment by adamchainz** [comment] 2017-05-04 20:30
How bizarre. `tox` is meant to be super reproducible 😢  Any more details, like your OS, might help.

Ultimately this error is from pytest complaining that it tried to import a conftest file but ended up importing from the virtualenv path instead. The `tests` directory/module isn't actually meant to be copied into the virtualenv path because it's ignored in `setup.py`. Potentially your version of `setuptools` is old and is not obeying `packages=find_packages(exclude=['tests', 'tests.*']),
`, but I doubt that. I assume you didn't add another package to one of the requirements files that happens to install a `tests.conftest` module. Try without your edits to the settings file. There's an outside chance that the file doesn't import properly and it's breaking the mechanism in pytest.

Otherwise, check the pytest issues for this: https://github.com/pytest-dev/pytest/issues?utf8=%E2%9C%93&q=ImportMismatchError%20 . I see they have one where they are discussing actually removing this check because it's easy to trigger under `tox`.

**Comment by adamchainz** [comment] 2017-05-28 11:46
Closing due to no update.

**Closed by adamchainz** 2017-05-28 11:46 UTC
