### ISSUE TITLE
Unable to use JSONField in mariadb

### ISSUE THREAD

**Issue by akhilputhiry** [adamchainz/django-mysql#422] opened 2018-01-29 17:30 UTC
Unable to use JSONField in mariadb

```
datasources.DataSource.metadata: (django_mysql.E016) MySQL 5.7+ is required to use JSONField
	HINT: At least one of your DB connections should be to MySQL 5.7+
datasources.DataSourceType.metadata: (django_mysql.E016) MySQL 5.7+ is required to use JSONField
	HINT: At least one of your DB connections should be to MySQL 5.7+
```

Django==2.0
django-mysql==2.2.0
MariaDB==10.2.12

**Comment by adamchainz** [comment] 2018-01-29 17:54
Duplicate of #342 , workaround there.

**Closed by adamchainz** 2018-01-29 17:54 UTC
