### ISSUE TITLE
WARNINGS: The character set is not utf8mb4 for database connection 'default'

### ISSUE THREAD

**Issue by tinyms** [adamchainz/django-mysql#384] opened 2017-08-23 10:44 UTC
Summary: *database connect default character set*

WARNINGS:
?: (django_mysql.W003) The character set is not utf8mb4 for database connection 'default'
        HINT: The default 'utf8' character set does not include support for all Unicode characters. It's strongly recommended you move to use 'utf8mb4'. See: https://djang
o-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w003-utf8mb4

Django Version: *Django 1.11.4*

Database and version used: *MySQL 5.7.19*

Version: *Django-MySQL 2.1.0*

**Comment by adamchainz** [comment] 2017-08-23 10:47
This is a warning raised by the library, have you tried to fix it?

**Comment by tinyms** [comment] 2017-08-23 11:16
I do not know how this error happened， no ability to fix it

**Comment by adamchainz** [comment] 2017-08-23 11:19
Please read the linked guide, https://django-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w003-utf8mb4 . The checks are mentioned in several places in the docs including the installation section: https://django-mysql.readthedocs.io/en/latest/installation.html#installation .

This is not an issue with django-mysql, it's doing exactly as intended, so I'm closing this issue.

**Closed by adamchainz** 2017-08-23 11:19 UTC
